### PR TITLE
Db seed

### PR DESCRIPTION
**Pull request by memcmahon**
Related Issue(s):

Changes Made:
Updates db/seed to format string dates from csv into date/time format

Reviewers:
@AtmaVichara or @garcia50

### CODE REVIEW

**Comment by memcmahon** [comment]
Hey @AliSchlereth and @icorson3, we have a couple of questions around the data in the conditions csv:
1. There are some rows in the csv data that do not have values in them for some attributes.  It looks like for every attribute, there is at least one record that is missing that piece of data.  Would you rather we use default values for these instances, or should we not validate every attribute?  If we should use a default, is there a value that you would prefer?

2. On the condition show page, we just want to confirm that you would like to have all 24 attributes present?

**Comment by AliSchlereth** [comment]
@memcmahon I recommend not validating presence on those attributes; however, you'll want to build it out so that any attribute that is present gets displayed on the show.

**Comment by memcmahon** [comment]
@AliSchlereth Thanks! We follow your recommendation.

**Comment by icorson3** [comment]
Also in the spec, we would like to see these attributes: `Date, Max Temperature, Mean Temperature, Min Temperature, Mean Humidity, Mean Visibility (in Miles), Mean Wind Speed (mph), Precipitation (inches)` @memcmahon

**Pull request merged**
